Script started on Mon Mar 12 17:53:27 2018
]0;~
[32mUSER@LAPTOP-6EMJVM6Q [33m~[0m
$ whoami; pwd
USER
/home/USER
]0;~
[32mUSER@LAPTOP-6EMJVM6Q [33m~[0m
$ git config -l
]0;~
[32mUSER@LAPTOP-6EMJVM6Q [33m~[0m
$ git clone https://github,com[1Pcom.com[C[C[C/<>E>2>4>0>6>3>1>5>5>[K[1PE24063155[C[C[C[C[C[C[C[C[C/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;~
[32mUSER@LAPTOP-6EMJVM6Q [33m~[0m
$ exit

Script done on Mon Mar 12 17:55:01 2018
